# 控制端配置
HOST = "localhost"
PORT = 5001

# 功能开关
ENABLE_SCREEN_CONTROL = True
ENABLE_FILE_MANAGEMENT = True
ENABLE_PROCESS_MANAGEMENT = True
ENABLE_COMMAND_EXECUTION = True

# 附加选项
ENABLE_STARTUP = False
ENABLE_HIDDEN = False 